// Applets
export const FETCHING_APPLET_DATA = "FETCHING_APPLET_DATA";
export const FETCHING_APPLET_DATA_SUCCESS = "FETCHING_APPLET_DATA_SUCCESS";
export const FETCHING_APPLET_DATA_FAIL = "FETCHING_APPLET_DATA_FAIL";

// Discovery
export const FETCHING_DISCOVERY_DATA = "FETCHING_DISCOVERY_DATA";
export const FETCHING_DISCOVERY_DATA_SUCCESS = "FETCHING_DISCOVERY_DATA_SUCCESS";
export const FETCHING_DISCOVERY_DATA_FAIL = "FETCHING_APPLET_DATA_FAIL";
