// Applets
export const FETCHING_APPLET_DATA = "FETCHING_APPLET_DATA";
export const FETCHING_APPLET_DATA_SUCCESS = "FETCHING_APPLET_DATA_SUCCESS";
export const FETCHING_APPLET_DATA_FAIL = "FETCHING_APPLET_DATA_FAIL";

// Discovery
export const FETCHING_DISCOVERY_DATA = "FETCHING_DISCOVERY_DATA";
export const FETCHING_DISCOVERY_DATA_SUCCESS = "FETCHING_DISCOVERY_DATA_SUCCESS";
export const FETCHING_DISCOVERY_DATA_FAIL = "FETCHING_DISCOVERY_DATA_FAIL";

// Search
export const FETCHING_SEARCH_DATA = "FETCHING_SEARCH_DATA";
export const FETCHING_SEARCH_DATA_SUCCESS = "FETCHING_SEARCH_DATA_SUCCESS";
export const FETCHING_SEARCH_DATA_FAIL = "FETCHING_SEARCH_DATA_FAIL";

// Create An Applet
export const CREATING_AN_APPLET = "CREATING_AN_APPLET";
export const CREATING_AN_APPLET_SUCCESS = "CREATING_AN_APPLET_SUCCESS";
export const CREATING_AN_APPLET_FAIL = "CREATING_AN_APPLET_FAIL";
