runtime: go
api_version: go1
application: requestHandler

handlers:
# - url: /stylesheets
#   static_dir: stylesheets
#
# - url: /(.*\.(gif|png|jpg))$
#   static_files: static/\1
#   upload: static/.*\.(gif|png|jpg)$

- url: /.*
  script: requestHandler
